# Generated by Django 6.0.3 on 2026-08-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcase', '0003_alter_aigenerationrecord_test_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(blank=True, max_length=255, verbose_name='用例标题')),
                ('start_url', models.CharField(blank=True, max_length=2048, verbose_name='起始 URL')),
                ('result', models.CharField(choices=[('running', '运行中'), ('pass', '通过'), ('fail', '失败'), ('error', '错误')], default='running', max_length=16, verbose_name='执行结果')),
                ('step_results', models.JSONField(blank=True, default=list, verbose_name='步骤结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_runs', to='testcase.testcase', verbose_name='关联功能用例')),
            ],
            options={
                'verbose_name': 'Web自动化执行记录',
                'verbose_name_plural': 'Web自动化执行记录',
                'ordering': ['-started_at'],
            },
        ),
    ]
