# Generated by Django 6.0.3 on 2026-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webautomationrun',
            name='environment_id',
            field=models.IntegerField(blank=True, help_text='关联「环境管理」中的环境（ApiEnvironment.id），记录执行所用环境', null=True, verbose_name='环境ID'),
        ),
    ]
