# Generated by Django 6.0.3 on 2026-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='用例标题')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=10, verbose_name='等级')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评估工时')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('automation_status', models.CharField(choices=[('not_analyzed', '未分析'), ('not_automated', '未自动化'), ('automated', '已自动化')], default='not_analyzed', max_length=20, verbose_name='是否自动化')),
                ('automation_case_id', models.CharField(blank=True, max_length=255, verbose_name='关联的自动化用例ID')),
                ('requirement', models.CharField(blank=True, max_length=500, verbose_name='关联需求')),
                ('precondition', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.TextField(blank=True, verbose_name='测试步骤')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('generation_source', models.CharField(choices=[('manual', '手动创建'), ('ai_generated', 'AI生成')], default='manual', max_length=20, verbose_name='生成来源')),
                ('ai_request_id', models.CharField(blank=True, max_length=100, verbose_name='AI请求ID')),
                ('ai_model_version', models.CharField(blank=True, max_length=50, verbose_name='AI模型版本')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='AI置信度')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('block', '阻塞'), ('skip', '跳过')], max_length=20, verbose_name='执行结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '用例执行记录',
                'verbose_name_plural': '用例执行记录管理',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用例库名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例库',
                'verbose_name_plural': '用例库管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='评审状态')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例评审',
                'verbose_name_plural': '用例评审管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '已归档')], default='active', max_length=20, verbose_name='版本状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模块名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块管理',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
