# Generated by Django 6.0.3 on 2026-08-05 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('requirement', '0002_initial'),
        ('testcase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_records', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='requirement.requirement', verbose_name='关联需求'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='aigenerationrecord',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_records', to='testcase.testcase', verbose_name='关联用例'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testcase.testcase', verbose_name='所属用例'),
        ),
        migrations.AddField(
            model_name='testcaserepository',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repositories', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcaserepository',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_repositories', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='previous_review',
            field=models.ForeignKey(blank=True, help_text='关联到上一轮被驳回的评审记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reviews', to='testcase.testcasereview', verbose_name='上一轮评审'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评审人'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='testcase.testcase', verbose_name='所属用例'),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='testcase.testcaserepository', verbose_name='所属用例库'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testcase.testcaseversion', verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='aigenerationrecord',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_records', to='testcase.testcaseversion', verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='testmodule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testcase.testmodule', verbose_name='父模块'),
        ),
        migrations.AddField(
            model_name='testmodule',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='testcase.testcaseversion', verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='testcase.testmodule', verbose_name='所在目录'),
        ),
        migrations.AddField(
            model_name='aigenerationrecord',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_records', to='testcase.testmodule', verbose_name='所属模块'),
        ),
        migrations.AddIndex(
            model_name='testcaseexecution',
            index=models.Index(fields=['test_case', 'result'], name='testcase_te_test_ca_aa3a09_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaseexecution',
            index=models.Index(fields=['executed_by'], name='testcase_te_execute_82952e_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaseexecution',
            index=models.Index(fields=['executed_at'], name='testcase_te_execute_494af8_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaserepository',
            index=models.Index(fields=['project'], name='testcase_te_project_091e06_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaserepository',
            index=models.Index(fields=['created_by'], name='testcase_te_created_ebf1be_idx'),
        ),
        migrations.AddIndex(
            model_name='testcasereview',
            index=models.Index(fields=['test_case', 'status'], name='testcase_te_test_ca_62eb38_idx'),
        ),
        migrations.AddIndex(
            model_name='testcasereview',
            index=models.Index(fields=['reviewer'], name='testcase_te_reviewe_247002_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaseversion',
            index=models.Index(fields=['repository', 'status'], name='testcase_te_reposit_762639_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaseversion',
            index=models.Index(fields=['is_default'], name='testcase_te_is_defa_9053b9_idx'),
        ),
        migrations.AddIndex(
            model_name='testmodule',
            index=models.Index(fields=['version', 'parent'], name='testcase_te_version_d22ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['version', 'priority'], name='testcase_te_version_12b368_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['version', 'automation_status'], name='testcase_te_version_64cf87_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['module'], name='testcase_te_module__2c4808_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['title'], name='testcase_te_title_53bc45_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['created_by'], name='testcase_te_created_777a93_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['priority'], name='testcase_te_priorit_f0ba3f_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['generation_source'], name='testcase_te_generat_f257e9_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['review_status'], name='testcase_te_review__6660cb_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationrecord',
            index=models.Index(fields=['version', 'status'], name='testcase_ai_version_0396d0_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationrecord',
            index=models.Index(fields=['test_case'], name='testcase_ai_test_ca_962762_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationrecord',
            index=models.Index(fields=['created_by'], name='testcase_ai_created_b45e52_idx'),
        ),
    ]
