# Generated by Django 6.0.3 on 2026-06-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasereview',
            name='previous_review',
            field=models.ForeignKey(blank=True, help_text='关联到上一轮被驳回的评审记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reviews', to='testcase.testcasereview', verbose_name='上一轮评审'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='revision_note',
            field=models.TextField(blank=True, help_text='重新提交评审时填写的修改说明', verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, help_text='表示这是第几轮评审，首次评审为1', verbose_name='评审轮次'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='review_status',
            field=models.CharField(choices=[('pending', '待评审'), ('approved', '已通过'), ('rejected', '已驳回'), ('revision_pending', '修改后待重审')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
