# Generated by Django 6.0.3 on 2026-08-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationrecord',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_records', to='testcase.testcase', verbose_name='关联用例'),
        ),
    ]
