# Generated by Django 6.0.3 on 2026-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='需求标题')),
                ('description', models.TextField(blank=True, verbose_name='需求描述')),
                ('func_point', models.CharField(blank=True, max_length=500, verbose_name='功能点')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('ai_extracted', 'AI提取')], default='manual', max_length=20, verbose_name='来源')),
                ('knowledge_base_id', models.CharField(blank=True, max_length=100, verbose_name='来源知识库ID')),
                ('knowledge_id', models.CharField(blank=True, max_length=100, verbose_name='来源文档ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='AI提取会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
