# Generated by Django 6.0.3 on 2026-08-05 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('requirement', '0001_initial'),
        ('testcase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requirements', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='testcase.testcaseversion', verbose_name='所属版本'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['project', 'status'], name='requirement_project_184539_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['project', 'priority'], name='requirement_project_6fb53d_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['source'], name='requirement_source_e7e0c6_idx'),
        ),
    ]
