"""
Django settings for Testbackend project.

Generated by 'django-admin start-project' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import warnings
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
_env_debug = os.environ.get('DJANGO_DEBUG', '').lower()
DEBUG = _env_debug in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_from_env = os.environ.get('DJANGO_SECRET_KEY')
if _secret_key_from_env:
    SECRET_KEY = _secret_key_from_env
elif DEBUG:
    SECRET_KEY = 'django-insecure-dev-only-key-please-set-django-secret-key-env'
    warnings.warn(
        "DJANGO_SECRET_KEY 环境变量未设置，正在使用开发用临时密钥。"
        "生产环境必须设置 DJANGO_SECRET_KEY 环境变量！",
        RuntimeWarning
    )
else:
    raise ValueError(
        "生产环境必须设置 DJANGO_SECRET_KEY 环境变量！"
    )

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "django_filters",
    "apps.users",
    "apps.projects",
    "apps.testcase",
    "apps.knowledge",
    "apps.apitest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware.request_logging.RequestLoggingMiddleware",
    "apps.core.middleware.rate_limit.RateLimitMiddleware",
    "apps.core.middleware.audit_log.AuditLogMiddleware",
]

# CORS 配置
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _cors_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(',') if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5174",
    ]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "Content-Type",
    "Authorization",
]

CORS_EXPOSE_HEADERS = ['Content-Disposition']

ROOT_URLCONF = "Testbackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Testbackend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (User uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "users.User"

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'apps.core.utils.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'apps.core.utils.exception_handler.custom_exception_handler',
}

# JWT Configuration
_jwt_secret_from_env = os.environ.get('JWT_SECRET')
if _jwt_secret_from_env:
    JWT_SECRET = _jwt_secret_from_env
elif DEBUG:
    JWT_SECRET = SECRET_KEY
    warnings.warn(
        "JWT_SECRET 环境变量未设置，正在使用 SECRET_KEY 作为 JWT 密钥。"
        "生产环境必须设置独立的 JWT_SECRET 环境变量！",
        RuntimeWarning
    )
else:
    raise ValueError(
        "生产环境必须设置独立的 JWT_SECRET 环境变量！"
    )
JWT_EXPIRATION_HOURS = int(os.environ.get('JWT_EXPIRATION_HOURS', 24))

# Frontend URL Configuration
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# WeKnora Knowledge Base Configuration
WEKNORA_BASE_URL = os.environ.get('WEKNORA_BASE_URL', 'http://127.0.0.1:3000/api/v1')
WEKNORA_API_KEY = os.environ.get('WEKNORA_API_KEY', '')
if not WEKNORA_API_KEY:
    if DEBUG:
        warnings.warn(
            "WEKNORA_API_KEY 环境变量未设置，知识库功能将无法使用。"
            "请设置 WEKNORA_API_KEY 环境变量！",
            RuntimeWarning
        )
    else:
        raise ValueError(
            "生产环境必须设置 WEKNORA_API_KEY 环境变量！"
        )

# WeKnora 默认模型配置
WEKNORA_DEFAULT_EMBEDDING_MODEL_ID = os.environ.get('WEKNORA_DEFAULT_EMBEDDING_MODEL_ID', '')
WEKNORA_DEFAULT_LLM_MODEL_ID = os.environ.get('WEKNORA_DEFAULT_LLM_MODEL_ID', '')

# WeKnora Agent 配置
WEKNORA_AGENT_TIMEOUT = int(os.environ.get('WEKNORA_AGENT_TIMEOUT', 120))
WEKNORA_DEFAULT_AGENT_ID = os.environ.get('WEKNORA_DEFAULT_AGENT_ID', 'builtin-smart-reasoning')

# AI TestCase Generator Service Configuration
AI_SERVICE_URL = os.environ.get('AI_SERVICE_URL', 'http://localhost:8001')
AI_SERVICE_TIMEOUT = int(os.environ.get('AI_SERVICE_TIMEOUT', 600))
AI_CACHE_ENABLED = os.environ.get('AI_CACHE_ENABLED', 'true').lower() in ('true', '1', 'yes')
AI_CACHE_TTL = int(os.environ.get('AI_CACHE_TTL', 3600))
AI_CLIENT_THREAD_POOL_SIZE = int(os.environ.get('AI_CLIENT_THREAD_POOL_SIZE', 10))

# API Testing Service Configuration (接口测试微服务)
API_TESTING_SERVICE_URL = os.environ.get('API_TESTING_SERVICE_URL', 'http://localhost:8002')
API_TESTING_SERVICE_TIMEOUT = int(os.environ.get('API_TESTING_SERVICE_TIMEOUT', 120))

# OpenAI Embedding Configuration (用于用例去重)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_BASE_URL = os.environ.get('OPENAI_BASE_URL', 'https://open.bigmodel.cn/api/paas/v4')
OPENAI_EMBEDDING_MODEL = os.environ.get('OPENAI_EMBEDDING_MODEL', 'embedding-3')
OPENAI_EMBEDDING_TIMEOUT = int(os.environ.get('OPENAI_EMBEDDING_TIMEOUT', 30))

# Caches Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

MAX_REQUEST_BODY_SIZE = int(os.environ.get('MAX_REQUEST_BODY_SIZE', 10 * 1024 * 1024))

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.qq.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)


def check_production_settings():
    errors = []
    
    if not DEBUG:
        if not os.environ.get('DJANGO_SECRET_KEY'):
            errors.append("生产环境必须设置 DJANGO_SECRET_KEY 环境变量")
        
        if not os.environ.get('DJANGO_ALLOWED_HOSTS'):
            errors.append("生产环境必须设置 DJANGO_ALLOWED_HOSTS 环境变量")
        
        if ALLOWED_HOSTS == ['localhost', '127.0.0.1']:
            errors.append("生产环境 ALLOWED_HOSTS 不应仅包含 localhost 和 127.0.0.1")
        
        if not os.environ.get('DJANGO_DEBUG'):
            errors.append("生产环境应显式设置 DJANGO_DEBUG=False")
        
        if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
            errors.append("生产环境不建议使用 SQLite 数据库")
    
    return errors


_settings_errors = check_production_settings()
if _settings_errors:
    for error in _settings_errors:
        warnings.warn(f"配置检查警告: {error}", RuntimeWarning)

# Production Security Settings
# These settings are only enabled when DEBUG=False
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
