# Generated by Django 6.0.3 on 2026-09-08 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCheckTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名')),
                ('repository_url', models.CharField(max_length=1024, verbose_name='仓库地址')),
                ('branch', models.CharField(blank=True, max_length=255, verbose_name='分支')),
                ('commit_sha', models.CharField(blank=True, max_length=64, verbose_name='Commit SHA')),
                ('service_task_id', models.CharField(max_length=64, unique=True, verbose_name='微服务任务ID')),
                ('trigger_source', models.CharField(choices=[('manual', '手动'), ('webhook', 'Webhook')], default='manual', max_length=16, verbose_name='触发来源')),
                ('case_source', models.CharField(choices=[('inline', '内联'), ('file', 'Excel'), ('platform', '平台')], default='platform', max_length=16, verbose_name='用例来源')),
                ('test_case_file', models.CharField(blank=True, max_length=255, verbose_name='Excel 文件名')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.CharField(blank=True, max_length=255, verbose_name='当前进度')),
                ('risk_level', models.CharField(blank=True, max_length=16, verbose_name='风险等级')),
                ('risk_score', models.IntegerField(default=0, verbose_name='风险分数')),
                ('risk_files', models.JSONField(blank=True, default=list, verbose_name='高风险文件')),
                ('risk_reason', models.TextField(blank=True, verbose_name='风险理由')),
                ('diff_info', models.JSONField(blank=True, default=dict, verbose_name='代码变更')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='汇总统计')),
                ('conclusion', models.CharField(choices=[('', '无'), ('passed', '通过'), ('blocked', '风险阻断'), ('failed', '未通过')], default='', max_length=16, verbose_name='结论')),
                ('gate_provider', models.CharField(blank=True, max_length=16, verbose_name='门禁平台')),
                ('gate_state', models.CharField(blank=True, max_length=16, verbose_name='门禁状态')),
                ('gate_response', models.JSONField(blank=True, default=dict, verbose_name='门禁响应')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_check_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_check_tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '代码检查任务',
                'verbose_name_plural': '代码检查任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(blank=True, max_length=64, verbose_name='用例编号')),
                ('testpoint', models.CharField(blank=True, max_length=512, verbose_name='测试点')),
                ('steps', models.TextField(blank=True, verbose_name='操作步骤')),
                ('expectation', models.TextField(blank=True, verbose_name='预期结果')),
                ('result', models.CharField(choices=[('通过', '通过'), ('失败', '失败'), ('异常', '异常'), ('解析失败', '解析失败'), ('未知', '未知')], default='未知', max_length=16, verbose_name='结果')),
                ('reason', models.TextField(blank=True, verbose_name='校验理由')),
                ('success', models.BooleanField(default=False, verbose_name='是否通过')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='codecheck.codechecktask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '用例检查结果',
                'verbose_name_plural': '用例检查结果',
                'ordering': ['id'],
            },
        ),
    ]
