# Generated by Django 6.0.3 on 2026-09-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecheckresult',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='证据位置'),
        ),
        migrations.AddField(
            model_name='codecheckresult',
            name='failure_reason',
            field=models.TextField(blank=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='codecheckresult',
            name='failure_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='失败类型'),
        ),
    ]
