# Generated by Django 6.0.3 on 2026-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecheck', '0002_codecheckresult_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechecktask',
            name='commit_author',
            field=models.CharField(blank=True, max_length=128, verbose_name='提交人'),
        ),
    ]
