# Generated by Django 6.0.3 on 2026-08-05 12:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：系统管理员', max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(help_text='如：admin', max_length=50, unique=True, verbose_name='角色代码')),
                ('type', models.CharField(choices=[('system', '系统角色'), ('default', '默认角色')], default='default', max_length=20, verbose_name='角色类型')),
                ('description', models.TextField(blank=True, help_text='角色功能描述', null=True, verbose_name='角色描述')),
                ('status', models.CharField(choices=[('active', '活跃'), ('disabled', '禁用'), ('deprecated', '已弃用')], default='active', max_length=20, verbose_name='角色状态')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='系统权限代码列表，如 ["system_admin", "user_manage"]', verbose_name='系统权限列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='角色创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统角色',
                'verbose_name_plural': '系统角色',
                'db_table': 'roles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='roles_code_25c050_idx'), models.Index(fields=['status'], name='roles_status_86510b_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='', help_text='显示用姓名', max_length=100, verbose_name='用户真实姓名')),
                ('phone', models.CharField(blank=True, help_text='可选联系方式', max_length=20, null=True, verbose_name='手机号码')),
                ('avatar', models.CharField(blank=True, help_text='用户头像图片地址', max_length=255, null=True, verbose_name='头像URL')),
                ('title', models.CharField(blank=True, help_text='如：高级前端工程师', max_length=100, null=True, verbose_name='职位/头衔')),
                ('email', models.EmailField(help_text='用户邮箱，用于登录和通知', max_length=254, unique=True, verbose_name='邮箱地址')),
                ('status', models.CharField(choices=[('active', '活跃'), ('disabled', '禁用'), ('suspended', '暂停'), ('pending', '待激活')], default='active', help_text='用户账户的当前状态', max_length=20, verbose_name='用户状态')),
                ('last_login_time', models.DateTimeField(blank=True, help_text='记录用户最后登录时间', null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.CharField(blank=True, help_text='记录用户最后登录IP地址', max_length=45, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用户注册时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, help_text='用户备注说明', null=True, verbose_name='备注信息')),
                ('reset_password_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='重置密码令牌')),
                ('reset_password_expire', models.DateTimeField(blank=True, null=True, verbose_name='重置密码令牌过期时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('system_role', models.ForeignKey(blank=True, help_text='关联roles.id，决定用户在平台全局的权限', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='系统角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(help_text='JWT唯一标识符', max_length=64, unique=True, verbose_name='Token ID')),
                ('token', models.CharField(blank=True, max_length=500, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入黑名单时间')),
                ('expires_at', models.DateTimeField(verbose_name='Token过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token黑名单',
                'verbose_name_plural': 'Token黑名单',
                'db_table': 'token_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['system_role'], name='users_system__b1351c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['jti'], name='token_black_jti_d790b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['user'], name='token_black_user_id_444aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['expires_at'], name='token_black_expires_07a99b_idx'),
        ),
    ]
