# Generated by Django 6.0.3 on 2026-06-08 11:36

from django.db import migrations, models


def set_default_permissions(apps, schema_editor):
    """为现有角色设置默认权限"""
    Role = apps.get_model('users', 'Role')

    # 系统权限定义
    ADMIN_PERMISSIONS = [
        'system_admin', 'system_settings',
        'user_manage', 'user_view',
        'role_manage', 'role_view',
        'project_create', 'project_view_all', 'project_delete_any',
        'report_global', 'report_export',
    ]
    USER_PERMISSIONS = ['project_create']

    # 更新 admin 角色
    Role.objects.filter(code='admin').update(permissions=ADMIN_PERMISSIONS)

    # 更新 user 角色
    Role.objects.filter(code='user').update(permissions=USER_PERMISSIONS)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='系统权限代码列表，如 ["system_admin", "user_manage"]', verbose_name='系统权限列表'),
        ),
        migrations.RunPython(set_default_permissions, migrations.RunPython.noop),
    ]
