# Generated by Django 6.0.3 on 2026-05-23 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('env_type', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('staging', '预发布'), ('prod', '生产环境')], default='test', max_length=20, verbose_name='环境类型')),
                ('base_url', models.CharField(help_text='如: http://api.example.com', max_length=500, verbose_name='基础URL')),
                ('description', models.TextField(blank=True, verbose_name='环境描述')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('token', 'Token'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('jwt', 'JWT'), ('api_key', 'API Key')], default='none', max_length=20, verbose_name='认证类型')),
                ('auth_token', models.TextField(blank=True, help_text='认证令牌，支持变量引用 {{token}}', verbose_name='认证Token')),
                ('auth_header', models.CharField(default='Authorization', help_text='如: Authorization、X-API-Key', max_length=100, verbose_name='认证请求头')),
                ('auth_username', models.CharField(blank=True, max_length=100, verbose_name='Basic Auth 用户名')),
                ('auth_password', models.CharField(blank=True, max_length=100, verbose_name='Basic Auth 密码')),
                ('default_headers', models.JSONField(default=dict, help_text='{"Content-Type": "application/json"}', verbose_name='默认请求头')),
                ('global_vars', models.JSONField(default=dict, help_text='如: {"api_key": "xxx", "default_user": "admin"}', verbose_name='全局变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_environments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API测试环境',
                'verbose_name_plural': 'API测试环境管理',
                'db_table': 'apitest_environment',
                'ordering': ['-is_default', 'env_type'],
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('path', models.CharField(help_text='如: /api/users/login（不含base_url）', max_length=500, verbose_name='接口路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='POST', max_length=10, verbose_name='请求方法')),
                ('description', models.TextField(blank=True, verbose_name='接口描述')),
                ('module', models.CharField(blank=True, help_text='如: 用户管理、订单管理', max_length=100, verbose_name='所属模块')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('headers', models.JSONField(default=dict, help_text='{"Content-Type": "application/json"}', verbose_name='请求头模板')),
                ('params', models.JSONField(default=dict, help_text='{"page": 1, "size": 10}', verbose_name='Query参数模板')),
                ('body_template', models.JSONField(default=dict, help_text='{"username": "{{username}}", "password": "{{password}}"}', verbose_name='请求体模板')),
                ('response_example', models.JSONField(default=dict, help_text='{"code": 0, "data": {...}}', verbose_name='响应示例')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='接口状态')),
                ('knowledge_base_id', models.CharField(blank=True, max_length=100, verbose_name='知识库ID')),
                ('knowledge_id', models.CharField(blank=True, max_length=100, verbose_name='知识ID')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('ai_generated', 'AI生成')], default='manual', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_infos', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API接口',
                'verbose_name_plural': 'API接口管理',
                'db_table': 'apitest_info',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=10, verbose_name='优先级')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('precondition', models.JSONField(default=list, help_text='\n        [\n            {"api_id": 1, "extract_vars": ["token", "user_id"]}\n        ]\n        ', verbose_name='前置接口')),
                ('steps', models.JSONField(default=list, help_text='\n        [\n            {\n                "order": 1,\n                "api_id": 1,\n                "api_name": "登录接口",\n                "path": "/api/users/login",\n                "method": "POST",\n                "headers": {},\n                "body": {"username": "{{username}}", "password": "{{password}}"},\n                "extract": {"token": "data.token"},\n                "assert": [{"field": "code", "value": 0}]\n            }\n        ]\n        ', verbose_name='测试步骤')),
                ('variables', models.JSONField(default=dict, help_text='{"username": "admin", "password": "123456"}', verbose_name='测试变量')),
                ('assertions', models.JSONField(default=list, help_text='\n        [\n            {"type": "status_code", "value": 200},\n            {"type": "json", "field": "code", "value": 0}\n        ]\n        ', verbose_name='断言规则')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('passed', '已通过'), ('failed', '已失败')], default='draft', max_length=20, verbose_name='状态')),
                ('knowledge_base_id', models.CharField(blank=True, max_length=100, verbose_name='知识库ID')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('ai_generated', 'AI生成')], default='manual', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='projects.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_api_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '接口测试用例',
                'verbose_name_plural': '接口测试用例管理',
                'db_table': 'apitest_case',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('running', '执行中'), ('cancelled', '已取消')], default='running', max_length=20, verbose_name='执行结果')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('step_results', models.JSONField(default=list, help_text='\n        [\n            {\n                "order": 1,\n                "api_name": "登录接口",\n                "request": {"method": "POST", "url": "...", "body": {...}},\n                "response": {"status_code": 200, "body": {...}},\n                "success": true,\n                "duration_ms": 150,\n                "extracted_vars": {"token": "xxx"}\n            }\n        ]\n        ', verbose_name='步骤执行结果')),
                ('variables_snapshot', models.JSONField(default=dict, verbose_name='变量快照')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('error_step', models.IntegerField(blank=True, null=True, verbose_name='出错步骤')),
                ('ai_validation', models.JSONField(blank=True, default=dict, help_text='{"passed": true, "reason": "...", "suggestions": [...]}', verbose_name='AI校验结果')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='apitest.apienvironment', verbose_name='执行环境')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='apitest.apitestcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '接口测试执行记录',
                'verbose_name_plural': '接口测试执行记录管理',
                'db_table': 'apitest_run',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='apienvironment',
            index=models.Index(fields=['project', 'env_type'], name='apitest_env_project_88022b_idx'),
        ),
        migrations.AddIndex(
            model_name='apienvironment',
            index=models.Index(fields=['project', 'is_default'], name='apitest_env_project_38a198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apienvironment',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='apiinfo',
            index=models.Index(fields=['project', 'module'], name='apitest_inf_project_4245e2_idx'),
        ),
        migrations.AddIndex(
            model_name='apiinfo',
            index=models.Index(fields=['project', 'method'], name='apitest_inf_project_05e3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='apiinfo',
            index=models.Index(fields=['status'], name='apitest_inf_status_702002_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['project', 'status'], name='apitest_cas_project_02ddae_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['project', 'priority'], name='apitest_cas_project_044bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['status'], name='apitest_cas_status_05b18a_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['test_case', 'result'], name='apitest_run_test_ca_889a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['environment'], name='apitest_run_environ_a7a96f_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['start_time'], name='apitest_run_start_t_25ed18_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['executed_by'], name='apitest_run_execute_48c51e_idx'),
        ),
    ]
