# Generated by Django 6.0.3 on 2026-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('env_type', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('staging', '预发布'), ('prod', '生产环境')], default='test', max_length=20, verbose_name='环境类型')),
                ('base_url', models.CharField(help_text='如: http://api.example.com', max_length=500, verbose_name='基础URL')),
                ('description', models.TextField(blank=True, verbose_name='环境描述')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('token', 'Token'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('jwt', 'JWT'), ('api_key', 'API Key')], default='none', max_length=20, verbose_name='认证类型')),
                ('auth_token', models.TextField(blank=True, help_text='认证令牌，支持变量引用 {{token}}', verbose_name='认证Token')),
                ('auth_header', models.CharField(default='Authorization', help_text='如: Authorization、X-API-Key', max_length=100, verbose_name='认证请求头')),
                ('auth_username', models.CharField(blank=True, max_length=100, verbose_name='Basic Auth 用户名')),
                ('auth_password', models.CharField(blank=True, max_length=100, verbose_name='Basic Auth 密码')),
                ('default_headers', models.JSONField(default=dict, help_text='{"Content-Type": "application/json"}', verbose_name='默认请求头')),
                ('global_vars', models.JSONField(default=dict, help_text='如: {"api_key": "xxx", "default_user": "admin"}', verbose_name='全局变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API测试环境',
                'verbose_name_plural': 'API测试环境管理',
                'db_table': 'apitest_environment',
                'ordering': ['-is_default', 'env_type'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='对应微服务的 apiname', max_length=200, verbose_name='用例名称')),
                ('precondition', models.TextField(blank=True, help_text='如: 用户已登录、数据已准备', verbose_name='前置条件')),
                ('testpoint', models.TextField(blank=True, default='', help_text='具体测试内容描述', verbose_name='测试点')),
                ('expectation', models.TextField(blank=True, default='', help_text='如: HTTP状态码200，返回code为0', verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=10, verbose_name='优先级')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('test_data', models.JSONField(blank=True, default=dict, help_text='如: {"username": "admin", "password": "123456"}', verbose_name='测试数据')),
                ('run_list', models.JSONField(blank=True, default=list, help_text='AI 分析的接口执行顺序，包含依赖接口', verbose_name='执行列表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('passed', '已通过'), ('failed', '已失败')], default='draft', max_length=20, verbose_name='状态')),
                ('knowledge_base_id', models.CharField(blank=True, max_length=100, verbose_name='知识库ID')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('ai_generated', 'AI生成')], default='manual', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '接口测试用例',
                'verbose_name_plural': '接口测试用例管理',
                'db_table': 'apitest_case',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('running', '执行中'), ('cancelled', '已取消')], default='running', max_length=20, verbose_name='执行结果')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('step_results', models.JSONField(default=list, help_text='每个接口的请求响应详情', verbose_name='步骤执行结果')),
                ('variables_snapshot', models.JSONField(default=dict, verbose_name='变量快照')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('error_step', models.IntegerField(blank=True, null=True, verbose_name='出错步骤')),
                ('ai_validation', models.JSONField(blank=True, default=dict, help_text='{"passed": true, "reason": "..."}', verbose_name='AI校验结果')),
            ],
            options={
                'verbose_name': '接口测试执行记录',
                'verbose_name_plural': '接口测试执行记录管理',
                'db_table': 'apitest_run',
                'ordering': ['-start_time'],
            },
        ),
    ]
