# Generated by Django 6.0.3 on 2026-08-05 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apitest', '0001_initial'),
        ('projects', '0001_initial'),
        ('testcase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apienvironment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='apienvironment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_environments', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_cases', to='testcase.testmodule', verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_api_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_cases', to='testcase.testcaseversion', verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='apitestrun',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='apitest.apienvironment', verbose_name='执行环境'),
        ),
        migrations.AddField(
            model_name='apitestrun',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='apitestrun',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='apitest.apitestcase', verbose_name='所属用例'),
        ),
        migrations.AddIndex(
            model_name='apienvironment',
            index=models.Index(fields=['project', 'env_type'], name='apitest_env_project_88022b_idx'),
        ),
        migrations.AddIndex(
            model_name='apienvironment',
            index=models.Index(fields=['project', 'is_default'], name='apitest_env_project_38a198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apienvironment',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['project', 'status'], name='apitest_cas_project_02ddae_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['project', 'priority'], name='apitest_cas_project_044bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['status'], name='apitest_cas_status_05b18a_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['test_case', 'result'], name='apitest_run_test_ca_889a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['environment'], name='apitest_run_environ_a7a96f_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['start_time'], name='apitest_run_start_t_25ed18_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestrun',
            index=models.Index(fields=['executed_by'], name='apitest_run_execute_48c51e_idx'),
        ),
    ]
