# Generated by Django 6.0.3 on 2026-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apiinfo',
            name='apitest_inf_project_4245e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiinfo',
            name='apitest_inf_project_05e3e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiinfo',
            name='apitest_inf_status_702002_idx',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='assertions',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='apitestcase',
            name='variables',
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='expectation',
            field=models.TextField(blank=True, default='', help_text='如: HTTP状态码200，返回code为0', verbose_name='预期结果'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='run_list',
            field=models.JSONField(blank=True, default=list, help_text='AI 分析的接口执行顺序，包含依赖接口', verbose_name='执行列表'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='test_data',
            field=models.JSONField(blank=True, default=dict, help_text='如: {"username": "admin", "password": "123456"}', verbose_name='测试数据'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='testpoint',
            field=models.TextField(blank=True, default='', help_text='具体测试内容描述', verbose_name='测试点'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='name',
            field=models.CharField(help_text='对应微服务的 apiname', max_length=200, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='precondition',
            field=models.TextField(blank=True, help_text='如: 用户已登录、数据已准备', verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='apitestrun',
            name='ai_validation',
            field=models.JSONField(blank=True, default=dict, help_text='{"passed": true, "reason": "..."}', verbose_name='AI校验结果'),
        ),
        migrations.AlterField(
            model_name='apitestrun',
            name='step_results',
            field=models.JSONField(default=list, help_text='每个接口的请求响应详情', verbose_name='步骤执行结果'),
        ),
        migrations.DeleteModel(
            name='ApiInfo',
        ),
    ]
