# Generated by Django 6.0.3 on 2026-08-05 20:00

import apps.apitest.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apienvironment',
            name='auth_password',
            field=apps.apitest.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Basic Auth 密码（落库加密存储）'),
        ),
        migrations.AlterField(
            model_name='apienvironment',
            name='auth_token',
            field=apps.apitest.fields.EncryptedTextField(blank=True, help_text='认证令牌，支持变量引用 {{token}}（落库加密存储）', verbose_name='认证Token'),
        ),
        migrations.AlterField(
            model_name='apienvironment',
            name='auth_username',
            field=apps.apitest.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Basic Auth 用户名（落库加密存储）'),
        ),
    ]
