# Generated by Django 6.0.3 on 2026-08-12 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_encrypt_environment_credentials'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apienvironment',
            name='target_type',
            field=models.CharField(choices=[('api', '接口测试'), ('web', 'Web 自动化')], default='api', help_text='接口测试 / Web 自动化', max_length=10, verbose_name='用途类型'),
        ),
        migrations.AddIndex(
            model_name='apienvironment',
            index=models.Index(fields=['project', 'target_type'], name='apitest_env_project_8aad84_idx'),
        ),
    ]
