# Generated by Django 6.0.3 on 2026-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('code', models.CharField(help_text='项目的唯一标识符', max_length=50, unique=True, verbose_name='项目标识')),
                ('identifier', models.CharField(blank=True, default='', help_text='项目URL标识', max_length=50, verbose_name='项目标识符')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('type', models.CharField(choices=[('web', 'Web项目'), ('mobile', '移动应用'), ('api', 'API项目'), ('desktop', '桌面应用'), ('performance', '性能测试'), ('security', '安全测试'), ('other', '其他')], default='web', max_length=20, verbose_name='项目类型')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('pending', '待开始'), ('archived', '已归档')], default='active', max_length=20, verbose_name='项目状态')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私有')], default='public', max_length=20, verbose_name='可见性')),
                ('icon', models.CharField(default='Folder', help_text='Element Plus 图标名称', max_length=50, verbose_name='项目图标')),
                ('icon_color', models.CharField(default='#3b82f6', max_length=20, verbose_name='图标颜色')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('knowledge_base_id', models.CharField(blank=True, help_text='关联的WeKnora知识库ID', max_length=100, null=True, verbose_name='知识库ID')),
                ('knowledge_base_name', models.CharField(blank=True, help_text='知识库显示名称', max_length=255, null=True, verbose_name='知识库名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('developer', '开发人员'), ('tester', '测试人员'), ('viewer', '观察者')], default='viewer', max_length=20, verbose_name='成员角色')),
                ('status', models.CharField(choices=[('active', '活跃'), ('disabled', '已禁用')], default='active', max_length=20, verbose_name='成员状态')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'db_table': 'project_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=20, verbose_name='角色标识')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='角色名称')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='角色颜色')),
                ('permissions', models.JSONField(default=list, help_text='权限代码列表', verbose_name='权限列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目角色权限',
                'verbose_name_plural': '项目角色权限',
                'db_table': 'project_roles',
                'ordering': ['role_key'],
            },
        ),
    ]
