# Generated by Django 6.0.3 on 2026-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='角色颜色'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role_key',
            field=models.CharField(max_length=20, verbose_name='角色标识'),
        ),
    ]
